blank_issues_enabled: false
contact_links:
  - name: ğŸŒ Website
    url: https://nykon.me/
    about: Check out my website
  - name: âœˆï¸ Telegram
    url: https://nykon.me/telegram
    about: My day-to-day life, thoughts and news
  - name: ğŸ’³ Patreon
    url: https://nykon.me/patreon
    about: You can support me and my work by donating
  
